version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nestjs-app:
    image: node:latest
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run start:dev


volumes:
  mongodb_data:
